[tox]
envlist = py
skipsdist = true

[testenv]
basepython = python
skip_install = true
deps = -r{toxinidir}/requirements-dev.txt
commands =
    pytest {posargs:tests}

[pytest]
asyncio_mode = auto
testpaths = tests
